all:
  hosts:
    serverldap:
      ansible_host: 127.0.0.1 
      ansible_port: 2222 
      ansible_ssh_private_key_file: ./.vagrant/machines/serverldap/virtualbox/private_key

    clientldap:
      ansible_host: 127.0.0.1 
      ansible_port: 2200 
      ansible_ssh_private_key_file: ./.vagrant/machines/clientldap/virtualbox/private_key
